### ISSUE TITLE
Failed to connect to livekit (localhost:7880)

### ISSUE THREAD

**Issue by Ashoka74** [livekit-examples/voice-assistant-frontend#15]
After connecting to Cloud from local files, I get this message when running in dev:

{"message":` "failed to connect to livekit, retrying in 4s: Cannot connect to host localhost:7880 ssl:default [The remote computer refused the network connection]", "level": "WARNING", "name": "livekit.agents", "timestamp": "2024-10-12T19:29:55.138077+00:00"}`

**Comment by Thameem-Mul-Ansari** [comment]
2025-11-14 10:08:09,024 - DEBUG asyncio - Using proactor: IocpProactor
2025-11-14 10:08:09,056 - DEV  livekit.agents - Watching C:\Users\thameemmulansari.s\Videos\DeligenceFabric-Hackathon
2025-11-14 10:08:17,424 - DEBUG asyncio - Using proactor: IocpProactor
2025-11-14 10:08:17,456 - INFO livekit.agents - starting worker {"version": "1.2.18", "rtc-version": "1.0.17"}
2025-11-14 10:08:17,456 - INFO livekit.agents - starting inference executor
2025-11-14 10:08:17,519 - INFO livekit.agents - initializing process {"pid": 11868, "inference": true}
2025-11-14 10:08:25,583 - DEBUG livekit.agents - initializing inference runner {"runner": "lk_end_of_utterance_multilingual", "pid": 11868, "inference": true}
2025-11-14 10:09:15,006 - INFO livekit.agents - process initialized {"pid": 11868, "inference": true, "elapsed_time": 57.49}
2025-11-14 10:09:15,006 - DEBUG livekit.agents - inference runner initialized {"runner": "lk_end_of_utterance_multilingual", "elapsed_time": 49.425420399995346, "pid": 11868, "inference": true}
2025-11-14 10:09:15,006 - DEBUG asyncio - Using proactor: IocpProactor {"pid": 11868, "inference": true}
2025-11-14 10:09:15,229 - WARNING livekit.agents - failed to connect to livekit, retrying in 0s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:15,307 - WARNING livekit.agents - failed to connect to livekit, retrying in 2s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:17,332 - WARNING livekit.agents - failed to connect to livekit, retrying in 4s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:21,380 - WARNING livekit.agents - failed to connect to livekit, retrying in 6s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:27,425 - WARNING livekit.agents - failed to connect to livekit, retrying in 8s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:35,448 - WARNING livekit.agents - failed to connect to livekit, retrying in 10s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:45,493 - WARNING livekit.agents - failed to connect to livekit, retrying in 10s
Traceback (most recent call last):
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\livekit\agents\worker.py", line 695, in _connection_task
    ws = await self._http_session.ws_connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thameemmulansari.s\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1084, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url='wss://meetai-79jngxk1.livekit.cloud/agent'
2025-11-14 10:09:47,973 - INFO livekit.agents - shutting down worker {"id": "unregistered"}
2025-11-14 10:09:47,973 - INFO livekit.agents - process exiting {"reason": "", "pid": 11868, "inference": true}
2025-11-14 10:09:48,233 - WARNING livekit.agents - exiting forcefully
Exception ignored in atexit callback: <function _exit_function at 0x00000130D0CCB7E0>
